config:
  clientId: SOOS_CLIENT_ID
  apiKey: SOOS_API_KEY
  projectName: 'SOOS DAST Analysis'
  scanMode: 'baseline'
  failOnError: 'continue_on_error'
  rules: ''
  context:
    file: ''
    user: ''
  apiURL: 'https://api.soos.io/api/'
  debug: false
  ajaxSpider: false
  apiScan:
    format: 'openapi'
